# 阿里云云效 Flow 配置文件
# 文档: https://help.aliyun.com/document_detail/153674.html

version: '1.0'
name: blog-valaxy-deploy
description: 构建并部署 Valaxy 博客到阿里云服务器

# 触发器：推送到 main 分支时触发
triggers:
  push:
    branches:
      - main

# 构建环境
runtimeStack:
  name: node
  version: 20

# 构建步骤
stages:
  - name: 构建阶段
    jobs:
      - name: 安装依赖
        steps:
          - run: npm install -g pnpm
          - run: pnpm install
      
      - name: 构建网站
        steps:
          - run: pnpm build:ssg
      
      - name: 打包产物
        steps:
          # 打包 dist 目录和部署脚本
          - run: tar -czf dist.tar.gz dist app-configs/

  - name: 部署阶段
    jobs:
      - name: 部署到服务器
        steps:
          # 上传到服务器
          - name: 上传构建产物
            uses: easydeploy/scp
            with:
              host: ${{ secrets.SERVER_HOST }}
              username: ${{ secrets.SERVER_USER }}
              password: ${{ secrets.SERVER_PASSWORD }}
              source: dist.tar.gz
              target: /tmp/
          
          # 执行部署脚本
          - name: 解压并部署
            uses: easydeploy/ssh
            with:
              host: ${{ secrets.SERVER_HOST }}
              username: ${{ secrets.SERVER_USER }}
              password: ${{ secrets.SERVER_PASSWORD }}
              script: |
                cd /www/wwwroot/blog_valaxy
                # 解压构建产物（包含 dist 和 app-configs）
                tar -xzf /tmp/dist.tar.gz
                # 设置权限
                chown -R www:www dist app-configs
                chmod -R 755 dist
                chmod +x app-configs/bin/appctl.sh
                # 使用 appctl.sh 脚本重启应用
                ./app-configs/bin/appctl.sh restart
                # 清理临时文件
                rm /tmp/dist.tar.gz
                echo "✅ 部署完成！"

# 环境变量（从云效密钥管理中读取）
# 需要在云效控制台配置以下密钥：
# - SERVER_HOST: 47.104.216.235
# - SERVER_USER: root
# - SERVER_PASSWORD: 你的服务器密码
