# 阿里云云效 Flow 配置文件
version: '1.0'
name: blog-valaxy-deploy
description: Valaxy 博客自动构建部署

# 触发条件
triggers:
  - type: push
    branch: main

# 环境变量
variables:
  - name: NODE_VERSION
    value: '20'
  - name: PNPM_VERSION
    value: '8'

# 构建步骤
steps:
  # 1. 检出代码
  - name: 检出代码
    type: checkout
    params:
      depth: 1

  # 2. 安装 Node.js
  - name: 安装 Node.js
    type: nodejs
    params:
      version: ${NODE_VERSION}

  # 3. 安装 pnpm
  - name: 安装 pnpm
    type: shell
    params:
      script: |
        npm install -g pnpm@${PNPM_VERSION}
        pnpm --version

  # 4. 安装依赖
  - name: 安装依赖
    type: shell
    params:
      script: |
        echo "📦 安装项目依赖..."
        pnpm install --frozen-lockfile

  # 5. 构建网站
  - name: 构建网站
    type: shell
    params:
      script: |
        echo "🔨 开始构建..."
        NODE_OPTIONS="--max-old-space-size=4096" pnpm build:ssg
        echo "✅ 构建完成"
        ls -lh dist/

  # 6. 打包产物
  - name: 打包产物
    type: shell
    params:
      script: |
        echo "📦 打包 dist 目录..."
        tar -czf dist.tar.gz dist
        ls -lh dist.tar.gz

  # 7. 上传到服务器
  - name: 部署到服务器
    type: deploy-host
    params:
      host: ${SERVER_HOST}
      username: ${SERVER_USER}
      password: ${SERVER_PASSWORD}
      port: 22
      source: dist.tar.gz
      target: /tmp/
      commands:
        - cd /www/wwwroot/blog_valaxy
        - rm -rf dist.backup
        - mv dist dist.backup 2>/dev/null || true
        - tar -xzf /tmp/dist.tar.gz
        - chown -R www:www dist
        - chmod -R 755 dist
        - rm /tmp/dist.tar.gz
        - nginx -s reload
        - echo "✅ 部署完成！"
        - echo "🌐 访问: https://kylaan.top"

# 通知配置
notifications:
  - type: dingtalk
    on_success: true
    on_failure: true
