name: GitHub Pages

on:
  push:
    branches:
      - main  # Or whichever branch you use for your source code

jobs:
  build-and-deploy: # Renamed job for clarity
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v3 # Updated to a newer version
        with:
          fetch-depth: 0

      - name: 🟢 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # Use a specific version of pnpm

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3 # Updated to a newer version
        with:
          node-version: '18' # Use a specific LTS version of Node.js
          cache: 'pnpm' # Enable caching for pnpm to speed up future runs

      - name: 📦 Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 🌌 Build Valaxy Blog
        run: pnpm run build

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true